### ISSUE TITLE
Support ARM Templates generation for MG scope deployment

### ISSUE THREAD

**Issue by KamilWiecek** [JimGBritt/AzurePolicy#18]
Exported ARM templates do not support deployment on management groups scope. Resource IDs used in dependsOn and policyDefinitions -> policyDefinitionId must be changed for this. The name of the MG must be known to build the ResourceId of the policy. I propose to create a variable into which we will insert a management group in which the scan is carried out.

I am happy to make these changes. @JimGBritt What do you think?

**Comment by JimGBritt** [comment]
@kwiecek thanks for providing feedback.  Please go ahead and make recommendations via a PR.  I recommend a parameter switch for ManagementGroup and parameter set association that would accept a parameter for MGID but I'm willing to look at anything you put together.  Do your best to keep in the theme of how the script is constructed as it is fairly well leveraged and I want to make sure we don't introduce any breaking changes that regress any functionality.  I'll be sure to document credit for your work once we are done.  Thank youl

**Comment by JimGBritt** [comment]
@kwiecek I've made a PR to do this just today here: https://github.com/JimGBritt/AzurePolicy/blob/jbritt-10-21-2020-MGSupport/AzureMonitor/Scripts/Create-AzDiagPolicy.ps1 which should support your needs.  I haven't heard from you but went ahead and starting working on this yesterday.  If I don't hear from you I will be merging this PR in the next 24 hours.  Your other issue - I'll make some comments on that because I need more details.

**Comment by JimGBritt** [comment]
Closing this one out @kwiecek as I just merged a new version.  Please take a look at the updates included in the synopsis for more information.  I also had to update some REST API logic due to some recent changes that seem to have occurred related to cached tokens.  Thank you for your input and collaboration on this update.
