### ISSUE TITLE
Add -IncludeAssignment switch

### ISSUE THREAD

**Issue by KamilWiecek** [JimGBritt/AzurePolicy#19]
The added functionality would ensure that the generated ARM Template would support the initiative assignment and permission assignment for MSI.

As in the previous issue, I would like to develop it.

**Comment by JimGBritt** [comment]
@kwiecek sure please make a PR on what you are thinking (similar to the other PR you are looking to do).  Thanks for the feedback and interest in improving.

**Comment by JimGBritt** [comment]
@kwiecek Is this something related to a PowerShell cmdlet or the script here?  Not sure - need more information on this one.  Can you share more specifics.  As it is you can do a new-azdeployment / or with recent PR staged new-azmanagementgroupDeployment to stage the policies and initiative and then assignment happens after in the portal or through CLI.  As far as I have seen there are no issues doing that.  But open to more details around this.

**Comment by KamilWiecek** [comment]
My idea is to add switch -IncudeAssignment and then create ARM Template with initiative and assignment resources.

**Comment by JimGBritt** [comment]
The benefit of the script is to provide a customer with visibility on drift and have the ability to create policies on the fly that can be integrated into a new Policy Initiative that represents current state.  I have purposely left off the assignment piece of this in the script.

**Comment by KamilWiecek** [comment]
Ok, then we can simply close, or provide a sample assignment ARM Template in the documentation. What do you think?

**Comment by JimGBritt** [comment]
@kwiecek I plan on providing some logic for Cross Sub / Assignment where the Log Analytics/Storage/EH is in one sub and the assignment is in another sub (or similar for MG) very soon.  This will hopefully give customers / partners the understanding of what additional things need to be done with RBAC and the managed identity in these scenarios to ensure that DINE policies can successfully remediate.  I hesitate in providing any sort of ARM template sample since it will be a treadmill of needing to ensure it works and is updated as most all of what I have on here is automatically updating which reduces upkeep.  Also I've purposely avoided Assignments as part of this specifically because I need to have the customer make the decision and roll that into their process.  I could reference something on your repo if that would work and reference it in the Readme.MD if you think that would work.  Let me know.
