### ISSUE TITLE
Question about Storage Diagnostics (Preview)

### ISSUE THREAD

**Issue by iisworks** [JimGBritt/AzurePolicy#39]
I noticed that diags setting gets enabled on v2 storage:
![image](https://user-images.githubusercontent.com/33196233/140502538-e82b52b5-cdf4-431c-8ddb-54eec932fdf7.png)

Is it somehow possible to include preview diags for Blob (e.g. Microsoft.Storage/storageAccounts/blobServices) from the exported template as well, or will this automatically become available once it gets GA?

**Comment by JimGBritt** [comment]
@iisworks great question - this one has been problematic because Azure Storage has implemented these sub resourceTypes (proxy resources) that are not trackable by ARM which means I cannot dynamically pick them up when the script runs. They aren't seen as a "resourceType" they are seen as a "ProxyResourceType" which is technically tied to the dependency of a Storage Account.  Therefore, the only way to pick these up is to scan every single storage account in a sub(s) and enumerate for proxy resoureceTypes - it is a heavy tax to support these currently.  There are some options I've considered such as asking for a ResourceID of a storage account that has all of these proxyresources enabled so that I can also find the categories, etc.  The good news is there are built ins (though they are currently being reworked) to be released soon I believe - a policy for each Proxy ResourceType and also for the Storage Account itself and these will be supported by the Storage Product Team.  At this point, I'd wait for those to become available.

**Comment by JimGBritt** [comment]
@iisworks btw I do have another open issue on this here: https://github.com/JimGBritt/AzurePolicy/issues/28 let me know if it is ok to close this one specifically and track this ask there.

**Comment by iisworks** [comment]
@JimGBritt Sorry about the duplicate, I completely overlooked the other one!
