### ISSUE TITLE
Is it an issue? 

### ISSUE THREAD

**Issue by mrbrutka** [JimGBritt/AzurePolicy#42]
Hello All,

Just used this code and I presumed that the newly created storage account will be with the diagnostic login, but it does not as per screenshot: 
![image](https://user-images.githubusercontent.com/96731072/147483816-a878c0a6-84ce-4a3e-a154-a8ea5700f527.png)

Then I created a ticket to MS asking why the policy does not work as should. 

They recommended me to use a build in policy named "Configure diagnostic settings for storage accounts to Log Analytics workspace"

Perhaps anyone had this "issue" or I misunderstood the functionality? 
I thought by creating policy and assigning a scope (creating assignment) the new storage account would have diagnostic logging as does build in policy? 
![image](https://user-images.githubusercontent.com/96731072/147484252-f01011c1-274d-41b5-902e-06440cdbce3d.png)

I am rather new to policies so sorry if all/any part of the description is not valid. I am just looking for answers.

**Comment by JimGBritt** [comment]
@mrbrutka apologies for just seeing this! I have been a bit buried on some things and actually have a PR I have been working on for an update and completely missed this issue - I apologize. One of the updates that I am making is actually to support proxy resource types for Azure storage (blobs, files, queues, tables) as they are untracked resources in ARM and cannot be programatically discovered easily due to some involved discussion :) but my update will contain the ability to configure storage account proxy resources in the future.  I don't know if your configuration above was configuring top level storage accounts or attempting to do the proxy resources. There is a built in policy that has been recently updated to support storage proxy resources provided by the storage team.  It is a bit different from the artifacts generated in this script but works well now I believe.  

Were you unblocked with the built-in policy to support your storage diagnostic logs challenges?

**Comment by mrbrutka** [comment]
Hello @JimGBritt, I discontinued troubleshooting this issue and did used the  built-in policy.
Thanks anyway!
